id:
  left: '00C33080957'
  right: '00C33080959'

base_line: "200"

set:
  # left camera
  # height: 1399.5  # !expr 1360. + 25. + 14.5
  # bias_x: 225.  # !expr 180. + 45.
  # bias_y: 395.  # !expr 40. + 355.
  bias: [225., 395., 1399.5]
  yaw: 0.
  roll: 3.0

param:
  Width: 1280
  Height: 640
  OffsetY: 384
  ExposureTime: 60000. # 64000.
  GammaEnable: True
  Gamma: 0.7
  BalanceWhiteAuto: 'Off'
  BalanceRatioR: 1249
  BalanceRatioG: 1024
  BalanceRatioB: 1546

calib:
  # camera1
  intrinsic1: [[1.273020955555724e+03,0,6.520438298015340e+02],
               [0,1.279186758868166e+03,2.609125169958485e+02],
               [0,0,1]]
  # param: distortion
  # with index [ k1 k2 p1 p2 (k3)]
  distortion1: [-0.057703347986055,0.098640709531910, 0, 0, 0]
  # camera2
  intrinsic2: [[1.269867594040952e+03,0,6.466840625573186e+02],
               [0,1.276065932767742e+03,2.487859175183317e+02],
               [0,0,1]]
  distortion2: [-0.055233878603078,0.093329796095413, 0, 0, 0]
  # param: R
  # right camera w.r.t left camera
  R: [[0.999852002791657,0.014850266915024,-0.008685740386663],
      [-0.014841753546608,0.999889310295429,0.001043795283599],
      [0.008700279603192,-9.147291866222404e-04,0.999961733470507]]
  T: [-2.010995109854422e+02,1.908971000814431,-0.738769640573549] # [-2.002816904638189e+02, 1.848291732897493, -0.638897175664680]










